// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKq9pey5GJlJcb_QarPVzyciU4XywskBw',
    appId: '1:1077762784882:web:87bbaa5c17b2bbf2208ceb',
    messagingSenderId: '1077762784882',
    projectId: 'monkeydetection-de11e',
    authDomain: 'monkeydetection-de11e.firebaseapp.com',
    databaseURL: 'https://monkeydetection-de11e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monkeydetection-de11e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu0M6TE9Ux5eiMDP_7PuiCg-wbCEigZvQ',
    appId: '1:1077762784882:android:ad9b96b850fbbff7208ceb',
    messagingSenderId: '1077762784882',
    projectId: 'monkeydetection-de11e',
    databaseURL: 'https://monkeydetection-de11e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monkeydetection-de11e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2FalBP6mKAQxhIlnHAidoNWVT9SeU9ow',
    appId: '1:1077762784882:ios:5e2bc7c159c3fd24208ceb',
    messagingSenderId: '1077762784882',
    projectId: 'monkeydetection-de11e',
    databaseURL: 'https://monkeydetection-de11e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monkeydetection-de11e.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2FalBP6mKAQxhIlnHAidoNWVT9SeU9ow',
    appId: '1:1077762784882:ios:5e2bc7c159c3fd24208ceb',
    messagingSenderId: '1077762784882',
    projectId: 'monkeydetection-de11e',
    databaseURL: 'https://monkeydetection-de11e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monkeydetection-de11e.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKq9pey5GJlJcb_QarPVzyciU4XywskBw',
    appId: '1:1077762784882:web:7286571f0232f434208ceb',
    messagingSenderId: '1077762784882',
    projectId: 'monkeydetection-de11e',
    authDomain: 'monkeydetection-de11e.firebaseapp.com',
    databaseURL: 'https://monkeydetection-de11e-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'monkeydetection-de11e.appspot.com',
  );
}
