name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  expandable: ^5.0.1
  firebase_core: ^2.30.1
  firebase_database: ^10.5.4
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.10+1
  flutter_tflite: ^1.0.1
  google_nav_bar: ^5.0.6
  image: ^3.2.0
  image_picker: ^0.8.5+3
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  syncfusion_flutter_charts: ^25.1.41+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
